<a href="https://colab.research.google.com/github/tiprock-network/predictbirthTime-ML/blob/main/Tensorflow_Decision_Forests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Tensorflow](https://github.com/tiprock-network/Machine-Learning-Python-and-tensor-flow-/blob/main/tf.png?raw=true)

# Decision Trees Using Tensorflow 
In this project I am exploring data with Regression 
* Using Tensorflow DT with one Variable as weight
* Using DT with multiple variables

In [13]:
#install tensor flow DT
!pip install tensorflow_decision_forests
!pip install wurlitzer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Import Tensorflow decision forest

In [12]:
import tensorflow_decision_forests as tfdf
import pandas as pd
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import math
#data load from local disk
from google.colab import files
uploaded=files.upload()



Saving labourward2.csv to labourward2 (1).csv


In [8]:
#load the data onto to either a pandas or numpy set
import io
dataframe = pd.read_csv(io.BytesIO(uploaded['labourward2.csv']))

In [9]:
dataframe.head()

systolic  diastolic   BMI  momWeight/10  timeValueinHrs
0       110         80  19.3          5.59           20.33
1       124         86  18.5          5.59            7.25
2       110         80  19.3          5.59           15.50
3       124         86  25.1          5.59            9.35
4       122         76  19.3          5.59           20.22

## Split the dataset
Split the dataset into train and test

In [15]:
#import sklearn and download
!pip install -U scikit-learn


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [16]:
def split_dataset(dataset, test_ratio=0.30):
  """Splits a panda dataframe in two."""
  test_indices = np.random.rand(len(dataset)) < test_ratio
  return dataset[~test_indices], dataset[test_indices]
#from sklearn.model_selection import train_test_split
train_set,test_set=split_dataset(dataframe)
print("{} examples in training, {} examples for testing.".format(
    len(train_set), len(test_set)))

71 examples in training, 30 examples for testing.


In [17]:
dataframe.head()

systolic  diastolic   BMI  momWeight/10  timeValueinHrs
0       110         80  19.3          5.59           20.33
1       124         86  18.5          5.59            7.25
2       110         80  19.3          5.59           15.50
3       124         86  25.1          5.59            9.35
4       122         76  19.3          5.59           20.22

In [19]:
# Name of the label column to be trained.
label = "timeValueinHrs"

#change into tensorflow dataframe
train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(train_set, label=label, task=tfdf.keras.Task.REGRESSION)
test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(test_set, label=label, task=tfdf.keras.Task.REGRESSION)

#### Training the Model for Regression

In [25]:


# Configure the model.
model_reg = tfdf.keras.RandomForestModel(task = tfdf.keras.Task.REGRESSION)#specifys task for regression

# Train the model.
model_reg.fit(x=train_ds)

Use /tmp/tmp37dhnc3r as temporary training directory
Reading training dataset...
Training dataset read in 0:00:00.199395. Found 71 examples.
Training model...
Model trained in 0:00:00.064868
Compiling model...
Model compiled.


In [59]:
#print train_ds
trains=np.stack(list(train_ds))
print(trains)

[[{'systolic': <tf.Tensor: shape=(71,), dtype=int64, numpy=
  array([110, 124, 122, 122, 110, 122, 110, 122, 122, 110, 110, 122, 124,
         124, 112, 112, 122, 122, 122, 126, 112, 110, 110, 124, 112, 110,
         122, 112, 120, 120, 112, 110, 122, 124, 112, 122, 122, 112, 122,
         122, 122, 124, 124, 122, 122, 120, 122, 124, 124, 120, 126, 122,
         124, 122, 124, 110, 126, 110, 112, 122, 122, 124, 122, 124, 112,
         112, 112, 110, 110, 124, 110])>, 'diastolic': <tf.Tensor: shape=(71,), dtype=int64, numpy=
  array([80, 86, 88, 88, 80, 92, 80, 92, 76, 80, 80, 76, 86, 86, 64, 64, 76,
         88, 88, 94, 64, 80, 80, 86, 64, 80, 76, 64, 90, 90, 64, 80, 92, 86,
         64, 76, 88, 64, 76, 88, 88, 86, 86, 92, 76, 90, 76, 86, 86, 90, 94,
         92, 86, 92, 86, 80, 94, 80, 64, 76, 76, 86, 76, 86, 64, 64, 64, 80,
         80, 86, 80])>, 'BMI': <tf.Tensor: shape=(71,), dtype=float64, numpy=
  array([19.3, 25.1, 25.1, 18.5, 24.3, 22.7, 19.3, 23.4, 19.3, 18.5, 22.7,
         

/usr/local/lib/python3.7/dist-packages/numpy/core/shape_base.py:420: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays = [asanyarray(arr) for arr in arrays]


In [124]:
tr=np.array(train_set)
print(tr.shape)

(71, 5)


In [126]:
#provide same size i.e train_ds
y_hat=model_reg.predict(train_ds,batch_size=None,verbose='auto',steps=None,callbacks=None,max_queue_size=10,workers=1)

#print the output of ten from len(train_set)
for i in range(10):
    res=float(y_hat[i])
    m=(round((res-int(res))*60,0))/100
    h=float(round(int(res)+m,2))
    

    if h>0.0 and h<12.0:
     
     print(f"{tr[i][0]}/{tr[i][1]}mm/Hg \t{tr[i][2]} BMI\t{tr[i][3]} kg  = Prediction: {h:0.2f} am")
    elif h>11.59 and h<23.59:
        h=round(h-12.00,2)#convert into 12hrs clock
        if h>=0.0 and h<=0.59:
         print(f"{tr[i][0]}/{tr[i][1]}mm/Hg \t{tr[i][2]} BMI\t{tr[i][3]} kg = Prediction: {h+12.00:0.2f} pm")
        elif h>0.59:
         print(f"{tr[i][0]}/{tr[i][1]}mm/Hg \t{tr[i][2]} BMI\t{tr[i][3]} kg = Prediction: {h:0.2f} pm")
    
    

1/1 [==============================] - 0s 39ms/step
110.0/80.0mm/Hg 	19.3 BMI	5.59 kg = Prediction: 2.54 pm
124.0/86.0mm/Hg 	25.1 BMI	5.59 kg = Prediction: 12.46 pm
122.0/88.0mm/Hg 	25.1 BMI	5.7 kg = Prediction: 12.02 pm
122.0/88.0mm/Hg 	18.5 BMI	5.7 kg = Prediction: 3.07 pm
110.0/80.0mm/Hg 	24.3 BMI	5.8 kg  = Prediction: 10.57 am
122.0/92.0mm/Hg 	22.7 BMI	5.8 kg  = Prediction: 10.31 am
110.0/80.0mm/Hg 	19.3 BMI	5.8 kg = Prediction: 2.47 pm
122.0/92.0mm/Hg 	23.4 BMI	5.8 kg  = Prediction: 10.28 am
122.0/76.0mm/Hg 	19.3 BMI	5.8 kg = Prediction: 2.42 pm
110.0/80.0mm/Hg 	18.5 BMI	6.0 kg = Prediction: 1.17 pm


#Model Evaluation

In [127]:
# Evaluate the model on the test dataset.
model_reg.compile(metrics=["mse"])
evaluation = model_reg.evaluate(test_ds, return_dict=True)

print(evaluation)
print()
print(f"MSE: {evaluation['mse']}")
print(f"RMSE: {math.sqrt(evaluation['mse'])}")

1/1 [==============================] - 0s 111ms/step - loss: 0.0000e+00 - mse: 23.3351
{'loss': 0.0, 'mse': 23.335054397583008}

MSE: 23.335054397583008
RMSE: 4.8306370591861905
