# Using Decision Trees for Regression Analysis
### Using multiple variables
* Blood Pressure
* BMI
* weight


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import copy

In [14]:
#dataframe
dataframe=pd.read_csv('labourward.csv')
df_features=pd.read_csv('labourward2.csv')
print(dataframe.head())
df_features.head()

   systolic  diastolic   BMI     time RAWWeight  momWeight/10  timeConv  \
0     122.0       92.0  19.7   9:30am     75kgs          7.50   9:30 AM   
1     110.0       80.0  18.5  10:20am     60kgs          6.00  10:20 AM   
2     122.0       76.0  20.1   8:20pm     77kgs          7.70   8:20 PM   
3     126.0       94.0  22.3   3:15pm   76.5kgs          7.65   3:15 PM   
4     124.0       86.0  20.2  12:10pm   62.4kgs          6.24  12:10 PM   

  time24HRS  timeValueinHrs  
0     09:30            9.50  
1     10:20           10.33  
2     20:20           20.33  
3     15:15           15.25  
4     12:10           12.17  


systolic  diastolic   BMI  momWeight/10  timeValueinHrs
0       110         80  19.3          5.59           20.33
1       124         86  18.5          5.59            7.25
2       110         80  19.3          5.59           15.50
3       124         86  25.1          5.59            9.35
4       122         76  19.3          5.59           20.22

In [4]:
#dataset shape
dataset=np.array(dataframe)
print(dataset.shape)

(101, 9)


In [30]:
#x=np.array(dataframe['momWeight/10']).reshape(-1,1)
#or
x=np.array(df_features[['systolic','diastolic','BMI','momWeight/10']])
print(x)

[[110.    80.    19.3    5.59]
 [124.    86.    18.5    5.59]
 [110.    80.    19.3    5.59]
 [124.    86.    25.1    5.59]
 [122.    76.    19.3    5.59]
 [122.    88.    25.1    5.7 ]
 [122.    88.    18.5    5.7 ]
 [110.    80.    24.3    5.8 ]
 [122.    92.    22.7    5.8 ]
 [110.    80.    19.3    5.8 ]
 [122.    92.    23.4    5.8 ]
 [122.    76.    19.3    5.8 ]
 [110.    80.    23.4    5.8 ]
 [110.    80.    18.5    6.  ]
 [110.    80.    22.7    6.  ]
 [122.    76.    25.1    6.1 ]
 [122.    76.    24.3    6.1 ]
 [124.    86.    20.2    6.24]
 [122.    76.    23.4    6.24]
 [124.    86.    19.3    6.24]
 [122.    76.    22.3    6.24]
 [124.    86.    25.1    6.24]
 [112.    64.    19.3    6.3 ]
 [112.    64.    25.1    6.3 ]
 [124.    86.    25.1    6.3 ]
 [122.    76.    23.4    6.32]
 [122.    88.    20.1    6.32]
 [122.    76.    23.4    6.32]
 [122.    88.    19.3    6.32]
 [126.    94.    23.4    6.32]
 [112.    64.    21.2    6.5 ]
 [110.    80.    22.3    6.5 ]
 [112.  

In [31]:
y=dataset[:,8] #1 D column expected
print(y)

[9.5 10.33 20.33 15.25 12.17 11.08 8.5 6.02 9.33 9.5 10.33 20.33 15.25
 12.17 11.08 8.5 6.02 9.33 11.23 9.07 6.33 9.22 12.38 15.5 16.5 12.38 9.35
 22.38 23.35 9.6 6.22 12.25 11.07 12.27 7.25 9.68 15.33 20.43 22.07 22.38
 23.35 9.6 6.22 12.25 11.07 12.27 7.25 9.68 15.33 20.43 22.07 15.5 16.5
 12.38 9.35 22.38 23.35 9.6 6.22 12.25 11.07 12.27 7.25 9.68 3.35 20.22
 11.23 9.07 6.33 9.22 12.38 15.5 16.5 12.38 9.35 22.38 23.35 9.6 6.22 17.5
 0.27 3.35 20.22 11.23 9.07 6.33 9.22 12.38 15.5 16.5 12.38 9.35 22.38
 23.35 21.27 10.37 9.25 16.27 9.38 22.27 6.02]


In [32]:
#divide into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100)

In [33]:
#import decision trees
from sklearn.tree import  DecisionTreeRegressor

#regressor object
reg=DecisionTreeRegressor(random_state=0)
#fitting parameter values
reg.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

Testing the model for output

In [45]:
y_hat=reg.predict(x_test)
for i in range(len(x_test)):
    res=y_hat[i]
    m=(round((res-int(res))*60,0))/100
    h=math.trunc(res)
    time=m+h
    if time>0.0 and time<12.0:
     
     print(f"{x_test[i][0]}/{x_test[i][1]}mm/Hg \t{x_test[i][2]} BMI\t{round(x_test[i][3]*10,2)} kg  = Prediction: {time:0.2f} am")
    elif time>11.59 and time<23.59:
        time=round(time-12.00,2)#convert into 12hrs clock
        if time>=0.0 and time<=0.59:
         print(f"{x_test[i][0]}/{x_test[i][1]}mm/Hg \t{x_test[i][2]} BMI\t{round(x_test[i][3]*10,2)} kg = Prediction: {time+12.00:0.2f} pm")
        elif time>0.59:
         print(f"{x_test[i][0]}/{x_test[i][1]}mm/Hg \t{x_test[i][2]} BMI\t{round(x_test[i][3]*10,2)} kg = Prediction: {time:0.2f} pm")
    

110.0/80.0mm/Hg 	19.3 BMI	68.0 kg  = Prediction: 6.13 am
122.0/76.0mm/Hg 	25.1 BMI	82.0 kg  = Prediction: 6.20 am
122.0/88.0mm/Hg 	20.1 BMI	63.2 kg  = Prediction: 8.30 am
122.0/88.0mm/Hg 	25.1 BMI	83.0 kg  = Prediction: 6.20 am
112.0/64.0mm/Hg 	22.7 BMI	68.0 kg = Prediction: 10.04 pm
122.0/76.0mm/Hg 	23.4 BMI	63.2 kg = Prediction: 10.23 pm
108.0/62.0mm/Hg 	24.3 BMI	68.0 kg  = Prediction: 7.15 am
110.0/80.0mm/Hg 	23.4 BMI	65.0 kg = Prediction: 10.23 pm
124.0/86.0mm/Hg 	22.7 BMI	75.0 kg = Prediction: 11.21 pm
124.0/86.0mm/Hg 	25.1 BMI	62.4 kg = Prediction: 4.30 pm
122.0/92.0mm/Hg 	19.7 BMI	75.0 kg = Prediction: 8.13 pm
112.0/64.0mm/Hg 	22.7 BMI	70.0 kg = Prediction: 10.04 pm
124.0/86.0mm/Hg 	20.1 BMI	70.7 kg = Prediction: 3.30 pm
122.0/88.0mm/Hg 	22.7 BMI	83.0 kg  = Prediction: 6.01 am
122.0/76.0mm/Hg 	23.4 BMI	82.0 kg  = Prediction: 6.01 am
110.0/80.0mm/Hg 	21.2 BMI	85.0 kg  = Prediction: 9.23 am
126.0/94.0mm/Hg 	19.3 BMI	73.0 kg = Prediction: 3.30 pm
122.0/88.0mm/Hg 	25.1 BMI	57.0 kg  

# Decision Tree Evaluation

In [46]:
#get the mean squared error root
from sklearn.metrics import mean_squared_error,mean_absolute_error
print(f"MSE root: {np.sqrt(mean_squared_error(y_test,y_hat))}")
print(f"MAE root: {mean_absolute_error(y_test,y_hat)}")

MSE root: 9.573808421537779
MAE root: 7.929999999999999
